### ISSUE TITLE
the code for SFG ？

### ISSUE THREAD

**Issue by ray-lee-94** [fbragman/Multi-Task#1]
《Stochastic Filter Groups for Multi-Task CNNs:
Learning Specialist and Generalist Convolution Kernels》
Where can I find your code for this paper?

**Comment by Nat-Sci** [comment]
Do you mind to share the codes?

**Comment by ggyyll** [comment]
> 《Stochastic Filter Groups for Multi-Task CNNs:
> Learning Specialist and Generalist Convolution Kernels》
> Where can I find your code for this paper?

Hello, did you find the code for this paper? If you have found, could you please share it with me? Thank you!

**Comment by Nat-Sci** [comment]
> > 《Stochastic Filter Groups for Multi-Task CNNs:
> > Learning Specialist and Generalist Convolution Kernels》
> > Where can I find your code for this paper?
> 
> Hello, did you find the code for this paper? If you have found, could you please share it with me? Thank you!

Examples of multi-task networks with SGF modules are here:
- VGG with SFG: https://github.com/fbragman/NiftyNet/blob/multitask_group/niftynet/network/vgg_mt_learned.py

BTW, if you think this repository is useful, please give your star to it.

**Comment by ggyyll** [comment]
> > > 《Stochastic Filter Groups for Multi-Task CNNs:
> > > Learning Specialist and Generalist Convolution Kernels》
> > > Where can I find your code for this paper?
> > 
> > 
> > Hello, did you find the code for this paper? If you have found, could you please share it with me? Thank you!
> 
> Examples of multi-task networks with SGF modules are here:
> 
> * VGG with SFG: https://github.com/fbragman/NiftyNet/blob/multitask_group/niftynet/network/vgg_mt_learned.py
> 
> BTW, if you think this repository is useful, please give your star to it.

Nice! Thanks for your sharing. I have given star to the repository.

**Comment by Nat-Sci** [comment]
> > > > 《Stochastic Filter Groups for Multi-Task CNNs:
> > > > Learning Specialist and Generalist Convolution Kernels》
> > > > Where can I find your code for this paper?
> > > 
> > > 
> > > Hello, did you find the code for this paper? If you have found, could you please share it with me? Thank you!
> > 
> > 
> > Examples of multi-task networks with SGF modules are here:
> > 
> > * VGG with SFG: https://github.com/fbragman/NiftyNet/blob/multitask_group/niftynet/network/vgg_mt_learned.py
> > 
> > BTW, if you think this repository is useful, please give your star to it.
> 
> Nice! Thanks for your sharing. I have given star to the repository.

You are welcome. Have fun.

**Comment by Imrankhan787** [comment]
Hello guys,
We have been trying to replicate this paper. We approached the authors of the Stochastic Filter Group. And they generously shared the code with us. But the problem is we cannot find the config.ini file in the code. Basically, config.ini is a config file that gives Niftynet the location of data +other options for output and hyperparameters. Any help in this regard will be greatly appreciated.

with best regards,
Imran Khan
